### ISSUE TITLE
Add Cheat sheets for Javascript

### ISSUE THREAD

**Issue by darkmatter18** [darkmatter18/cheatsheet#16]
- Add as many as cheat sheets, you want.
- Only `images` and `PDFs`
- Must add in the relevant directory.
- Add new sheets in the main `README.md` content list

Happy Contributing 🎉

**Comment by yashi12** [comment]
Hey! I would like to work on it. Can u plz assign it to me.

**Comment by darkmatter18** [comment]
@jordanhilado @yashi12 Both you guys can work, just add as much as sheets you want

**Comment by yashi12** [comment]
> @jordanhilado @yashi12 Both you guys can work, just add as much as sheets you want

I have added JS cheatsheet Pdf with hyperlinks(for easy navigation), Screenshots and One liner Syntax.
Please have a look at the PR(#24), and please merge it.

**Comment by jordanhilado** [comment]
Also added multiple more JS cheatsheets, mine is at PR(#27), thank you!

**Comment by yashi12** [comment]
@darkmatter18 please view my PR, thank you!

**Comment by yashi12** [comment]
@darkmatter18 plz view the PR(#24)

**Comment by kausthubmayuram** [comment]
@darkmatter18
Have raised a pull request. Please check and if you find any changes you want to suggest, please let me know.
Thanks

**Comment by vansh106** [comment]
I have raised a pull request for JavaScript . I uploaded around 70 cheatsheets for JavaScript . Please check it out it contains nearly everything which can be performed in JavaScript.
