### ISSUE TITLE
Add cheatsheet for VS code

### ISSUE THREAD

**Issue by darkmatter18** [darkmatter18/cheatsheet#21]
- Add as many as cheatsheets, you want.
- Only `images` and `PDFs`
- Must add in the [Code Editor](https://github.com/darkmatter18/cheatsheet/tree/master/Code%20Editors) directory.

Happy Contributing 🎉

**Comment by Kunal1198** [comment]
Hi can I work on this.

**Comment by xsro** [comment]
Can I add keyboard-shortcuts-reference from [VSCode docs](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference) to this repo

**Comment by thalelinh** [comment]
I don't know if you want to keep this issue open forever, but it seems that it got sorted with
https://github.com/darkmatter18/cheatsheet/pull/29
https://github.com/darkmatter18/cheatsheet/pull/23
and some more in https://github.com/darkmatter18/cheatsheet/pull/25
