### ISSUE TITLE
Add Cheatsheets

### ISSUE THREAD

**Issue by darkmatter18** [darkmatter18/cheatsheet#5]
- Add as many as cheatsheets, you want.
- Only `images` and `PDFs`
- Must add in the relevant directory.
- Add new sheets in `README.md` content list

Happy Contributing 🎉

**Comment by yash3001** [comment]
I want to work on it. Also can we add a section for linux?

**Comment by darkmatter18** [comment]
@yash3001 Yes, we can add as many as we want

**Comment by yashi12** [comment]
I want to work on it. Can we add a section of Node.js/Express into it?

**Comment by yashi12** [comment]
@darkmatter18 Can u please tell if I can add XML cheatsheet to it

**Comment by AliHaider20** [comment]
Can we make a cheatsheets of coding interview questions questions?

**Comment by ujjwalsingh-17** [comment]
@darkmatter18 can i make a cheatsheet for vscode?

**Comment by AryanNayak** [comment]
Hey, can I contribute to the issue by making a cheat sheet for frequently asked coding questions in an interview?

**Comment by darkmatter18** [comment]
> Hey, can I contribute to the issue by making a cheat sheet for frequently asked coding questions in an interview?

Go for it

**Comment by kaitou-1412** [comment]
Hey, I have made a SQL tutorials repository. 
May I contribute by adding it's link in the SQL Cheatsheet section ?
