### ISSUE TITLE
Hacktoberfest 2021 🎉🎊

### ISSUE THREAD

**Issue by darkmatter18** [darkmatter18/cheatsheet#60]
<p align="center"><img width="70%" src="https://hacktoberfest.digitalocean.com/_nuxt/img/logo-hacktoberfest-full.f42e3b1.svg"/></p>

<h1 align="center">Cheat Sheet</h1>

<p align="center">Cheat Sheet is delighted to welcome all the Hacktoberfest  2021 participants. 🎉🎊🥳 Make your way to one of the easiest repositories of all Github.</p>

> There are plenty of ways to contribute to this repository

1. Add your own issues and make a PR on that issue.
2. Add a Cheat Sheet of any programming language.
3. Add a Cheat Sheet of any library or framework.
4. Tiding the Repository by simply altering the _**README**_ files.

<h3 align="center">If you like the initiative, then don't forget to star ⭐ the repository. </h3>

### Some issues to work on:
#61 #68

**Comment by Geralt-Of-Rivia-Witcher** [comment]
Hey @darkmatter18, I just made a PR [#89 ](https://github.com/darkmatter18/cheatsheet/pull/89)
Please review it.

**Comment by Geralt-Of-Rivia-Witcher** [comment]
Hey @darkmatter18, I just made PR #98 and added cheatsheets for several languages.
please review.
