### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by darkmatter18** [darkmatter18/cheatsheet#61]
CONTRIBUTING.md plays a critical role when it comes to guiding contributors around the world.

The task of the issue is to add a **CONTRIBUTNG.md** file.

Make sure:
1. The file is at the root of the repo.
2. The name of the file must be **CONTRIBUTNG.md**
3. Add all the information you think is needed
4. The guideline should be beginner-friendly.
5. It should contain information like, how to fork, how to make a PR.
6. Try to add as many visuals as possible.
7. Mention this issue, when you make a PR.

The closing date on the issue is **_10th October 2021_**.
All the contributors are requested to make PRs within the date.

The best PR will be merged.

**Comment by Mridulbirla13** [comment]
Hey, I would like to contribute to this issue.

**Comment by bhairavee23** [comment]
is this issue still open?
