### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by darkmatter18** [darkmatter18/cheatsheet#68]
README.md is the most crucial when it comes to representing the Repository to others. Our README file is there but is not that perfect. 

So, the task of this PR is to **decorate and redesign the main root level `README.md` file**

1. Play with the decoration, whatever you like
2. Make it developer-friendly. 
3. Try to organize the content.
4. Add Badges and other visuals to make it more appeling.

The closing date on the issue is **_11th October 2021_**.

All the contributors are requested to make PRs within the date.

`The best PR will be merged.`

**Comment by nilis24** [comment]
Hello, I would like to work on this issue. Can you assign it to me please?

**Comment by darkmatter18** [comment]
@nilis24 Go for it

**Comment by evansusu** [comment]
I am willing to work on this, please assign it to me.

**Comment by karimabuseer** [comment]
Hey! Just wanted to say I'm happy to contribute here if @evansusu needs any support 🚀

**Comment by bhairavee23** [comment]
is this issue being worked upon? else do assign it to me

**Comment by karimabuseer** [comment]
It wasn't assigned to me, think @evansusu still has it assigned to them

**Comment by SubhamPanda2003** [comment]
Hey, I am willing to work on this, please assign this to me.

**Comment by jrmy911** [comment]
Same here, if needed I can contribute. :)
